defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - learning_rate_monitor.yaml
  - _self_

learning_rate_monitor:
  logging_interval: step

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: val/${monitor}
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: val/${monitor}
  patience: 10
  mode: "min"

model_summary:
  max_depth: -1
